protected/models/Author.php
<?php

class Author extends AwsApiSubModel {
	public static $avSizes = array(50, 150);
	const AV_SIZE_DEFAULT = 150;
	
	public $_id;
	public $display_name;
	public $avatar;
	public $gplus_uid;
	public $description;
	
	public function getId() {
		return $this->_id;
	}
	
	public function getAvatar($size=self::AV_SIZE_DEFAULT) {
		$size = intval($size);
		if (!$this->avatar)
			return false;
		
		$uploadAwsPattern = '/^(https?:\/\/upload\.allwomenstalk\.com\/avatar\/)(\d+)(\/.*)/i';
		if ( preg_match($uploadAwsPattern, $this->avatar) ) {
			//find best of allowed sizes (the one with minimal difference)
			foreach (self::$avSizes as $s)
				$diff[$s] = abs($size-$s);
			$size = array_keys($diff, min($diff));
			
			$url = preg_replace($uploadAwsPattern, '${1}'.$size[0].'$3', $this->avatar);
		} else {
			$url = Utils::addQueryArg('s', $size, $this->avatar);
		}
		
		return $url;
	}
	
	public function getPostsLink() {
		return Yii::app()->createUrl('author/archive', array(
			'site'=>Yii::app()->urlManager->defaultSite,
			'name'=>$this->id
		));
	}
	
	public function getGPlusLink() {
		if (!isset($this->gplus_uid))
			return false;
		return 'https://plus.google.com/'.$this->gplus_uid.'?rel=author';
	}
	
}

protected/models/Post.php
<?php

/**
 * General model that represents the posts.
 * 
 * @property string $id MongoDB ID of the post.
 * @property string $permalink URL of the post.
 * @property string $category Name of the first category.
 * @property string $categoryUrl URL of the first category.
 * @property string|false $postImage URL of the full-size post image.
 * @property Author $author Author model.
 */
class Post extends AwsApiModel {
	
	public $_id;
	public $host;
	public $blog;
	public $slug;
	public $post_title;
	public $post_date;
	public $image;
	public $comment_count;
	public $likes;
	public $categories = array();
	
	public function subModels() {
		return array(
			'author' => 'Author',
		);
	}
	
	/**
	 * Returns the static model of the specified API model class.
	 * 
	 * @return AwsApiModel The static model class.
	 */
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	/**
	 * Initializes this model.
	 */
	public function init() {
		$this->blog = Yii::app()->urlManager->defaultSite;
		if (preg_match('#^https?://([^.]+)\.allwomenstalk\.com#i', $this->host, $matches)) {
			$this->blog = $matches[1];
		}
		if ($this->blog==='www')
			$this->blog = Yii::app()->urlManager->defaultSite;
	}
	
	/**
	 * Returns MongoDB ID of the post.
	 * 
	 * @return string
	 */
	public function getId() {
		return $this->_id->{'$id'};
	}
	
	/**
	 * Returns link to the post.
	 * 
	 * @param int $page number of post`s page
	 * @return string
	 */
	public function getPermalink($page=0) {
		$params = array(
			'site'=>$this->blog,
			'name'=>$this->slug,
		);
		if (!empty($page))
			$params['page'] = intval($page)+1;
		return Yii::app()->urlManager->createUrl('post/view', $params);
	}
	
	/**
	 * Returns first category name.
	 * 
	 * @return string
	 */
	public function getCategory() {
		$cat = reset($this->categories);
		return $cat? ucfirst($cat->id) : '';
	}
	
	/**
	 * Returns first category archive URL.
	 * 
	 * @return string
	 */
	public function getCategoryUrl() {
		$cat = reset($this->categories);
		return $cat? Yii::app()->urlManager->createSiteUrl($cat->id) : '#';
	}
	
	/**
	 * Returns URL of the post image of the specified size.
	 * 
	 * Checks that image is actually exists if it is located on the current blog.
	 * Location of images and mapping from size identifiers to subdirectories should be specified
	 * in the application configuration.
	 * 
	 * @param string $size Image size identifier.
	 * @return string|boolean URL or false if image is not found.
	 */
	public function getPostImage($size='full') {
		if (!$this->image)
			return false;
		
		$imgSize = trim(Yii::app()->params['postImageSizes'][$size], '/');
		if ($imgSize!=='')
			$imgSize .= '/';
		
		//check for existance of images from current blog only
		/*if ( Yii::app()->urlManager->currentSite === $this->blog ) {
		$file = Yii::getPathOfAlias("webroot").'/'.$imgBase.$imgSize.$this->image;
		if ( !is_file($file) )
			return false;
		}*/
		
		$blog = ($this->blog===Yii::app()->urlManager->defaultSite)? 'www' : $this->blog;
		return 'http://img.allw.mn/'.$blog.'/thumbs/'.$imgSize.$this->image;
	}
}

protected/controllers/PostController.php
<?php

class PostController extends Controller {
	
	public $layout='//layouts/column2';
	private $_model;
	
	public function actionView($name, $page=1) {
        $page = intval($page)-1;
        $this->loadModel(Yii::app()->urlManager->currentSite, $name);
		if(!isset($this->_model->post_content[$page])) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}

        $this->_model->page = $page;
        $this->pageTitle = $this->_model->title.' | '.Yii::app()->name;
        $this->_model->getOpenGraphData($this->openGraph);
        
        $this->parselyMeta->title = $this->_model->title;
        $this->parselyMeta->link = $this->_model->permalink;
        $this->parselyMeta->image_url = $this->_model->postImage;
        $this->parselyMeta->type = 'post';
        $this->parselyMeta->post_id = $this->_model->id;
        $this->parselyMeta->pub_date = $this->_model->post_date;
        $this->parselyMeta->section = $this->_model->category;
        $this->parselyMeta->author = $this->_model->author->display_name;
        $this->parselyMeta->tags = $this->_model->tags;

        $this->awsL10n['postID'] = $this->_model->id;
        $this->awsL10n['postName'] = $name;
        $this->awsL10n['postImage'] = $this->_model->getPostImage();
        $this->awsL10n['postTitle'] = $this->_model->post_title;
        $this->awsL10n['isArchive'] = '';
        $this->awsL10n['isSingle'] = 1;
        $this->awsL10n['isHome'] = '';
        $this->awsL10n['pageNumber'] = $page;
        
        //adjusted to always point to actually current site, not that blog from where the post came
        $this->awsL10n['baseURL'] = 
        	Yii::app()->urlManager->createUrl('post/view', array(
        		'site'=>Yii::app()->urlManager->currentSite,
        		'name'=>$this->_model->slug,
        	));

		$related = $this->loadRelatedPosts($this->_model->id);
		$this->render('view', array('post'=>$this->_model, 'related'=>$related));
	}

    public function loadModel($blog, $name) {
		if ( $this->_model === null ) {
			$this->_model = SinglePost::model()->findByName($blog, $name);
			if ($this->_model===null)
				throw new CHttpException(404, 'The requested page does not exist.');
		}
		return $this->_model;
	}
	
	public function loadRelatedPosts($id) {
		$related = ArchivePost::model()->findRelated($id, 5);
		
		return $related? $related : array();
	}
	
	public function getPost() {
		return $this->_model;
	}
	
}

protected/views/post/_bottom.php
<?php
$this->renderPartial('/adv/sides');

protected/views/post/_comments.php
<div id="comments" class="sidebar-widget">

<div id="more-comments" style="display: none;"><button name="more-comments" class="bt-btn">Load more comments</button></div>
<div class="loading-icon"><div class="spinner">1</div></div>
<div id="comments-list"></div>

</div>

protected/views/post/_image.php
<?php
/* @var $post SinglePost */

//defaults: full size, wrap and link
if (!isset($size))
	$size = 'full';
$wrap = !isset($wrap) || !empty($wrap);
$link = !isset($link) || !empty($link);

$src = $post->getPostImage($size);
if ($src===false)
	return;

$image = CHtml::image($src, strip_tags($post->post_title), array(
	'class'=>'post-image size-'.$size,
));

if ($link)
	$image = CHtml::link($image, $post->permalink, array(
		'title'=>strip_tags($post->post_title),
		'class'=>'post-image-link link-size-'.$size,
	));

if ( isset($title) )
	$image = $title.$image;

if ($wrap)
	$image = CHtml::tag('div', array(
		'class'=>'post-image-wrap wrap-size-'.$size,
	), $image);

echo $image;

protected/views/post/_meta.php
<?php
/* @var $this PostController */
/* @var $post SinglePost */
/* @var $author Author */
?>
<div id="single-author-block">
	<?php if ($av=$author->getAvatar(80)): ?>
	<div class="image">
		<?php echo CHtml::image($av, $author->display_name, array(
			'class'=>'avatar avatar-80 photo',
			'width'=>32,
			'height'=>32,
		)); ?>
	</div>
	<button name="like-post" id="post-likes" class="bt-btn"> <?php
		echo Utils::shortenInt($post->likes);
	?></button>
	<?php endif; ?>
	<div>
		By <?php echo CHtml::link(CHtml::encode($author->display_name), $author->postsLink, array(
			'title'=>'Posts by '.$author->display_name,
			'rel'=>'author',
		)); ?>
	</div>
	<?php
	if ($gPlus=$author->gPlusLink)
		echo CHtml::link(
				CHtml::encode($author->display_name.' Google+'),
				$gPlus,
				array('class'=>'author-gplus')
			);
	?>
	<div class="counter">
		<span class="time">
			<?php echo Utils::timeAgo($post->post_date); ?>
		</span>
		<?php if ($post->comment_count>0): ?>
		<span class="comments"> <?php
			echo Utils::shortenInt($post->comment_count);
		?></span>
		<?php endif; ?>
	</div>
</div>

protected/views/post/_pagination.php
<?php
/* @var $post SinglePost */
?>
<div class="post-box paging paging-bottom">
    <noscript><ul>
        <?php
        for ($i = 0, $c = sizeof($post->post_content); $i < $c; $i++) {
            if ($i == 0 || $i == $post->page) {
                continue;
            } ?>
            <li><a href="<?php echo $post->getPermalink($i); ?>"><?php echo CHtml::encode($post->getTitleForPage($i, $post->post_title)); ?></a></li>
            <?php } ?>
    </ul></noscript>
</div>

protected/views/post/_related.php
<?php
/* @var $this Controller */
/* @var $post SinglePost */
?>
<div class="slide">
	<a href="<?php echo CHtml::encode($post->permalink); ?>">
		<img alt="<?php echo CHtml::encode(strip_tags($post->post_title)); ?>" data-src="<?php echo CHtml::encode($post->getPostImage('full')); ?>">
		<div><span><?php echo CHtml::encode($post->post_title); ?></span></div>
	</a>
</div>

protected/views/post/_sidebar.php
<?php
/* @var $this PostController */
?>
<span class="sidebar-close" data-icon="D"></span>

<?php
$this->renderPartial('/post/_comments');

protected/views/post/_tags.php
<?php
/* @var $post SinglePost */
?>
   <div id="tags" class="post-box tags"><?php
       for($i=0,$c=sizeof($post->tags);$i<$c;$i++) {
        if($i == 3) { ?><span class="hidden-tags"><?php } ?>
       <a rel="tag" href="<?php echo $post->getTaglink($post->tags[$i])?>"><?php echo ConvertData::extractName($post->tags[$i]) ?></a>
           <?php }
       if($c > 3) { ?>
       </span>
       <a class="switch-tags" href="#">+</a>
       <?php } ?>
   </div>

protected/views/post/view.php
<?php
/* @var $this PostController */
/* @var $post SinglePost */
?>
<div class="post">
	<?php
	$title = strip_tags($post->post_title);
	$title_html = CHtml::tag(
		$post->page>0 ? 'strong' : 'h1',
		array('class' => 'entry-title'),
		CHtml::link($title, $post->permalink, array('title' => $title))
	);
	
	if ($post->page>0) {
		echo $title_html;
	} else {
		$this->renderPartial('_image', array(
			'post'=>$post,
			'size'=>'full',
			'wrap'=>true,
			'link'=>false,
			'title'=>$title_html
		));
	}
	?>
	
	<div id="content">
        <div id="page-<?php echo $post->page + 1 ?>" class="post-page">
        <div class="post-box">
        <?php
		//TODO: anti-XSS filtering
		echo preg_replace('/<!--more(.*?)?-->/', $this->renderPartial('/adv/post-more', array('post'=>$post), true), $post->content);
		?>
        </div>
        </div>
	</div>
	
	<div id="share"><span>Pass it on via </span>
            <a href="#" id="soc-fb">Facebook</a> <a href="#" id="soc-tw">Twitter</a> <a href="#" id="soc-em">Email</a>
	</div>
	
    <?php $this->renderPartial('_pagination', array('post'=>$post)); ?>

    <?php $this->renderPartial('/adv/post-after', array('post'=>$post)); ?>
	
	<div id="popular-comments" class="post-box">
		<div class="spinner">1</div>
		<div id="show-comments">
			<button name="show-comments" class="bt-link">See all comments</button>
		</div>
	</div>
	
	<?php $this->renderPartial('_tags', array('post'=>$post)); ?>
	
	<?php if (!empty($related)): ?>
		<div id="related"><div class="slider">
		<?php
		foreach ($related as $p) {
			$this->renderPartial('_related', array('post'=>$p));
		}
		?>
		</div></div>
	<?php endif; ?>

</div>